FROM {{ build_image }} AS build
RUN apk update && apk add openjdk11 maven git
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
ENV MAVEN_HOME=/usr/share/maven
ENV PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
RUN mkdir /src && cd /src && git clone {{ app_repo }}
RUN apk update && apk add openjdk11 maven git
WORKDIR /src/Sample-Web-App/
RUN mvn package
FROM {{ run_image }}

RUN apk add --no-cache openjdk17-jre bash wget curl ca-certificates tzdata && \
    update-ca-certificates


ENV TOMCAT_VERSION=9.0.90
ENV    TOMCAT_HOME=/opt/tomcat
ENV    PATH=$TOMCAT_HOME/bin:$PATH

RUN wget -q https://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -O /tmp/tomcat.tar.gz && \
    tar -xzf /tmp/tomcat.tar.gz -C /opt && \
    mv /opt/apache-tomcat-${TOMCAT_VERSION} $TOMCAT_HOME && \
    rm /tmp/tomcat.tar.gz
COPY --from=build /src/Sample-Web-App/target/*.war /opt/tomcat/webapps

RUN addgroup -S tomcat && \
    adduser -S tomcat -G tomcat && \
    chown -R tomcat:tomcat $TOMCAT_HOME && \
    chmod +x $TOMCAT_HOME/bin/*.sh

EXPOSE 8080 9404

WORKDIR $TOMCAT_HOME
USER tomcat
CMD ["/opt/tomcat/bin/catalina.sh", "run"]